
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mytodo-api-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mytodo-be
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
