
apiVersion: v1
kind: Service
metadata:
  name: mytodo-be
  labels:
    app: mytodo-be
spec:
  type: ClusterIP
  selector:
    app: mytodo-be
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 8001
      targetPort: 8001
      name: metrics
