apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytodo-be
spec:
  template:
    spec:
      containers:
      - name: mytodo-be
        image: 409447267116.dkr.ecr.ap-south-1.amazonaws.com/mytodo_dev_ecr
