# image:
#   registry: github.io
#   repository: dandydev/redis-ha
#   tag: 7.2.5-debian-12-r0
#   pullPolicy: IfNotPresent


## Global override to ensure all sub-components use the legacy repo
global:
  imageRegistry: docker.io
  # Older charts may require this to allow using the legacy unmaintained repo
  security:
    allowInsecureImages: true 

image:
  repository: bitnamilegacy/redis
  # Explicitly set the tag to a known legacy version
  tag: 7.2.5-debian-12-r4 

sentinel:
  enabled: true # Ensure this matches your deployment type
  image:
    repository: bitnamilegacy/redis-sentinel
    tag: 7.2.5-debian-12-r4
