apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mytodo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/snagurum/myTodo_argocd_gitops
    targetRevision: main
    path: apps/mytodo-be/overlay/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      # name: dev-mytodo-be
      jsonPointers:
        - /spec/replicas