apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: letsencrypt-prod
spec:
  acme:
    email: admin@snagurum.in
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key

    solvers:
      - http01:
          ingress:
            class: nginx