apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-full-object-access-sa-name
  namespace: prod-mytodo
---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-timestamp-uploader
spec:
  # Runs every hour at minute 0 (0 * * * *)
  schedule: "* * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: s3-full-object-access-sa-name
          containers:
          - name: aws-cli
            image: amazon/aws-cli:latest
            # We use /bin/sh -c to run the script logic
            command: ["/bin/sh", "-c"]
            args:
              - |
                BUCKET_NAME=$1
                TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                echo "$TIMESTAMP" > "$TIMESTAMP"
                echo "Uploading $TIMESTAMP to s3://$BUCKET_NAME/test/..."
                aws s3 cp "$TIMESTAMP" "s3://${BUCKET_NAME}/test/${TIMESTAMP}"
              - "--"
              - "mytodo-poc-terraform-state"
          restartPolicy: OnFailure
