apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secret-storage-provider.yaml
  - nginx-ingress.yaml
  - cluster-issuer.yaml
  # - mytodo-be-namespace.yaml #don't create ns, its created in infrastructure code.

patches:
  - path: patch-deployment.yaml
  - path: delete-mytodo-be-configmap.yaml


namePrefix: prod-
namespace: prod-mytodo

labels:
- pairs:
    environment: prod
  includeSelectors: true
  includeTemplates: true