apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: mytodo
  # namespace: prod-mytodo

spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "/mytodo/prod/ACCESS_TOKEN_EXPIRE_MINUTES"
        objectType: "ssmparameter"
        objectAlias: "ACCESS_TOKEN_EXPIRE_MINUTES"

      - objectName: "/mytodo/prod/ALGORITHM"
        objectType: "ssmparameter"
        objectAlias: "ALGORITHM"

      - objectName: "/mytodo/prod/CORS_ALLOWED_ORIGINS"
        objectType: "ssmparameter"
        objectAlias: "CORS_ALLOWED_ORIGINS"

      - objectName: "/mytodo/prod/DATABASE_URL"
        objectType: "ssmparameter"
        objectAlias: "DATABASE_URL"

      - objectName: "/mytodo/prod/REDIS_URL"
        objectType: "ssmparameter"
        objectAlias: "REDIS_URL"

      - objectName: "/mytodo/prod/SECRET_KEY"
        objectType: "ssmparameter"
        objectAlias: "SECRET_KEY"

  secretObjects:
    - secretName: prod-mytodo
      type: Opaque
      data:
        - objectName: ACCESS_TOKEN_EXPIRE_MINUTES
          key: ACCESS_TOKEN_EXPIRE_MINUTES
        - objectName: ALGORITHM
          key: ALGORITHM
        - objectName: CORS_ALLOWED_ORIGINS
          key: CORS_ALLOWED_ORIGINS
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: REDIS_URL
          key: REDIS_URL
        - objectName: SECRET_KEY
          key: SECRET_KEY