apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/snagurum/myTodo_argocd_gitops
      targetRevision: HEAD
      ref: local-files
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 19.6.4
    # repoURL: 'https://dandydeveloper.github.io/charts/'
    # chart: redis-ha
    # targetRevision: 4.35.10 
      helm:
        valueFiles:
          - $local-files/platform/base/redis/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: redis

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true