apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/snagurum/myTodo_argocd_gitops
      targetRevision: HEAD
      ref: local-files
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 69.7.1
      helm:
        valueFiles:
          - $local-files/platform/base/kube-prometheus/values.yaml
      # Optional: Add custom values here just like a values.yaml file
      # values: |
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
