grafana:
  adminPassword: "password"
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      # url: http://loki:3100
      url: http://loki-gateway.loki.svc.cluster.local
      jsonData:
        derivedFields: []